FROM python:3.13-slim

WORKDIR /app

COPY . .

ARG CAGELEDGER_VERSION=unknown

ENV CAGELEDGER_HOST=0.0.0.0
ENV CAGELEDGER_PORT=5173
ENV CAGELEDGER_DB=/app/data/cageledger.sqlite
ENV CAGELEDGER_VERSION=${CAGELEDGER_VERSION}
ENV CAGELEDGER_REPOSITORY_URL=https://git.cellnucle.us/hugo/cageledger
ENV CAGELEDGER_BRANCH=main
ENV CAGELEDGER_UPDATE_CHECK_ENABLED=false
ENV CAGELEDGER_GITEA_TOKEN=

EXPOSE 5173

CMD ["python3", "server.py"]
