FROM python:3.13-slim

WORKDIR /app

COPY . .

ARG CAGELEDGER_VERSION=unknown

ENV CAGELEDGER_HOST=0.0.0.0
ENV CAGELEDGER_PORT=5173
ENV CAGELEDGER_DB=/app/data/cageledger.sqlite
ENV CAGELEDGER_VERSION=${CAGELEDGER_VERSION}
ENV CAGELEDGER_REPOSITORY=Hugo-YH/CageLedger
ENV CAGELEDGER_BRANCH=main

EXPOSE 5173

CMD ["python3", "server.py"]
