export const queryKeys = {
  session: ["session"] as const,
  bootstrap: (scope: string, roomId = "") => ["bootstrap", scope, roomId] as const,
  cageRoom: (roomId: string) => ["bootstrap", "room", roomId] as const,
  dashboardOverview: (month?: string) => ["dashboard-overview", month ?? "default"] as const,
  intakeRoot: ["intake"] as const,
  intake: (filters: Record<string, unknown>) => ["intake", "list", filters] as const,
  quantitySheets: (filters: Record<string, unknown>) => ["quantity-sheets", filters] as const,
  quantitySheetsRoot: ["quantity-sheets"] as const,
  quantitySheetPiHistory: (iacuc: string, beforeMonth: string) =>
    ["quantity-sheets", "pi-history", iacuc, beforeMonth] as const,
  quantitySheetRooms: ["quantity-sheet-rooms"] as const,
  settlementCandidatesRoot: ["billing-settlement-candidates"] as const,
  settlementCandidates: (filters: Record<string, unknown>) => ["billing-settlement-candidates", filters] as const,
  workflows: (filters: Record<string, unknown>) => ["billing-workflows", filters] as const,
  workflowFundingBookOptions: (workflowId: string) =>
    ["billing-workflows", workflowId, "funding-book-options"] as const,
  reimbursementRoot: ["reimbursement-records"] as const,
  reimbursements: (filters: Record<string, unknown>) => ["reimbursement-records", filters] as const,
  reimbursement: (id: string) => ["reimbursement-records", "detail", id] as const,
  reimbursementLedgerRoot: ["reimbursement-ledger"] as const,
  reimbursementObligations: (filters: Record<string, unknown>) =>
    ["reimbursement-ledger", "obligations", filters] as const,
  reimbursementClaims: (filters: Record<string, unknown>) => ["reimbursement-ledger", "claims", filters] as const,
  reimbursementClaim: (id: string) => ["reimbursement-ledger", "claim", id] as const,
  reimbursementLegacy: (filters: Record<string, unknown>) => ["reimbursement-ledger", "legacy", filters] as const,
  users: ["users"] as const,
  infrastructure: ["infrastructure"] as const,
  principalIdentities: ["principal-identities"] as const,
  iacucStatus: ["iacuc-index", "status"] as const,
  iacucExpiry: ["iacuc-index", "expiry"] as const,
  iacucSearch: (q: string, limit: number) => ["iacuc-index", "search", q, limit] as const,
  auditEvents: (filters: Record<string, unknown>) => ["audit-events", filters] as const,
  systemInfo: ["system", "info"] as const,
  systemEnvironment: ["system", "environment"] as const,
  systemUpdate: ["system", "update"] as const,
  animalInspectionCatalog: ["animal-inspection-catalog"] as const,
  animalInspectionCatalogDraft: ["animal-inspection-catalog", "draft"] as const,
  animalInspectionCatalogVersions: ["animal-inspection-catalog", "versions"] as const,
  animalInspectionsRoot: ["animal-inspections"] as const,
  animalInspections: (filters: Record<string, unknown>) => ["animal-inspections", filters] as const,
  animalInspection: (id: string) => ["animal-inspections", "detail", id] as const,
  animalFindingsRoot: ["animal-inspection-findings"] as const,
  animalFindings: (filters: Record<string, unknown>) => ["animal-inspection-findings", filters] as const,
};
