export const queryKeys = {
  session: ["session"] as const,
  bootstrap: (scope: string, roomId = "") => ["bootstrap", scope, roomId] as const,
  cageRoom: (roomId: string) => ["bootstrap", "room", roomId] as const,
  intakeRoot: ["intake"] as const,
  intake: (filters: Record<string, unknown>) => ["intake", "list", filters] as const,
  quantitySheets: (filters: Record<string, unknown>) => ["quantity-sheets", filters] as const,
  quantitySheetsRoot: ["quantity-sheets"] as const,
  quantitySheetRooms: ["quantity-sheet-rooms"] as const,
  workflows: (filters: Record<string, unknown>) => ["billing-workflows", filters] as const,
  reimbursementRoot: ["reimbursement-records"] as const,
  reimbursements: (filters: Record<string, unknown>) => ["reimbursement-records", filters] as const,
  reimbursement: (id: string) => ["reimbursement-records", "detail", id] as const,
  users: ["users"] as const,
  infrastructure: ["infrastructure"] as const,
  principalIdentities: ["principal-identities"] as const,
  iacucStatus: ["iacuc-index", "status"] as const,
  auditEvents: (filters: Record<string, unknown>) => ["audit-events", filters] as const,
  systemInfo: ["system", "info"] as const,
  systemUpdate: ["system", "update"] as const,
};
