import { ensureTestInfrastructure, expect, openQuantityEntry, openSavedQuantitySheets, test } from "./fixtures";

test("save and delete a quantity sheet in the ephemeral database", async ({ page }) => {
  await page.goto("/");
  await page.getByLabel("用户名", { exact: true }).fill("admin");
  await page.getByLabel("密码", { exact: true }).fill("admin123");
  await page.getByRole("button", { name: "登录", exact: true }).click();
  await expect(page.getByRole("heading", { name: "实验动物笼位管理与计费系统", exact: true })).toBeVisible();
  await ensureTestInfrastructure(page);
  await openQuantityEntry(page);
  const iacucInput = page.getByRole("combobox", { name: "IACUC 编号", exact: true });
  await iacucInput.fill("Z202506");
  await expect(page.locator('#quantity-iacuc-options option[value="Z2025063"]')).toHaveCount(1);
  await page.getByRole("combobox", { name: "房间号", exact: true }).selectOption({ label: "8014" });
  await expect(page.getByLabel("登记人员", { exact: true })).toHaveValue("系统管理员");
  await expect(page.getByLabel("登记人员", { exact: true })).toHaveAttribute("readonly", "");
  await expect(page.getByLabel("房间管理员", { exact: true })).toHaveValue("E2E 房间管理员");
  await expect(page.getByLabel("房间管理员", { exact: true })).toHaveAttribute("readonly", "");
  await page.getByRole("button", { name: /计费扩展选项/ }).click();
  await page.getByRole("checkbox", { name: "全额减免", exact: true }).check();
  await iacucInput.fill("E2E-IACUC-001");
  await page.locator("form").getByLabel("项目负责人", { exact: true }).fill("E2E负责人");
  await page.getByLabel("第 1 行结余笼数", { exact: true }).fill("2");
  await page.getByRole("button", { name: "保存统计表", exact: true }).click();
  await expect(page.getByRole("heading", { name: "确认保存数量统计表", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "确认保存", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("统计表已保存");
  await expect(page.getByRole("combobox", { name: "房间号", exact: true })).toHaveValue("");
  await expect(page.getByRole("combobox", { name: "IACUC 编号", exact: true })).toHaveValue("");
  await expect(page.locator("form").getByLabel("项目负责人", { exact: true })).toHaveValue("");
  await expect(page.getByLabel("第 1 行结余笼数", { exact: true })).toHaveValue("");
  await openSavedQuantitySheets(page);
  await expect(page.getByRole("heading", { level: 1, name: "已保存数量统计表", exact: true })).toBeVisible();
  const savedRow = page.getByRole("row", { name: /E2E-IACUC-001/ });
  await expect(savedRow).toBeVisible();
  await expect(savedRow).toContainText("系统管理员");
  await savedRow.getByRole("checkbox", { name: "选择 E2E-IACUC-001" }).check();
  const downloadPromise = page.waitForEvent("download");
  await page.locator(".quantity-saved-panel").getByRole("button", { name: "导出 PDF", exact: true }).click();
  const download = await downloadPromise;
  expect(download.suggestedFilename()).toBe("实验动物数量统计表 2026年07月 E2E-IACUC-001.pdf");
  await savedRow.getByRole("button", { name: "删除", exact: true }).click();
  await page.getByRole("button", { name: "确认删除", exact: true }).click();
  await expect(savedRow).toHaveCount(0);
});
