export type WorkspaceView =
  | "dashboard"
  | "cages"
  | "intake-entry"
  | "intake-batches"
  | "cage-card-scanner"
  | "billing-cage-map"
  | "billing-quantity-entry"
  | "billing-quantity-saved"
  | "billing-settlement"
  | "billing-monthly-summary"
  | "workflow-center"
  | "rooms"
  | "data"
  | "system"
  | "users"
  | "logs";
