WORKFLOW_STATUS_IN_FEEDING = "in_feeding"
WORKFLOW_STATUS_GENERATED = "statement_generated"
WORKFLOW_STATUS_SENT = "statement_sent"
WORKFLOW_STATUS_SIGNED = "statement_signed_returned"
WORKFLOW_STATUS_FINANCE = "submitted_to_finance"
WORKFLOW_STATUS_ARCHIVED = "statement_archived"
WORKFLOW_STATUS_LOCKED = "statement_locked"
WORKFLOW_STATUSES = (
    WORKFLOW_STATUS_IN_FEEDING,
    WORKFLOW_STATUS_GENERATED,
    WORKFLOW_STATUS_SENT,
    WORKFLOW_STATUS_SIGNED,
    WORKFLOW_STATUS_FINANCE,
    WORKFLOW_STATUS_ARCHIVED,
    WORKFLOW_STATUS_LOCKED,
)
VERSION_STATUS_ACTIVE = "active"
VERSION_STATUS_VOIDED = "voided"
