INDEX_STATEMENTS = (
    "CREATE INDEX IF NOT EXISTS idx_racks_room_id ON racks(room_id)",
    "CREATE INDEX IF NOT EXISTS idx_cage_slots_rack_id ON cage_slots(rack_id)",
    "CREATE INDEX IF NOT EXISTS idx_cage_slots_status ON cage_slots(status)",
    "CREATE INDEX IF NOT EXISTS idx_occupancies_slot_id ON occupancies(slot_id)",
    "CREATE INDEX IF NOT EXISTS idx_occupancies_room_id ON occupancies(room_id)",
    "CREATE INDEX IF NOT EXISTS idx_occupancies_rack_id ON occupancies(rack_id)",
    "CREATE INDEX IF NOT EXISTS idx_occupancies_iacuc ON occupancies(iacuc)",
    "CREATE INDEX IF NOT EXISTS idx_occupancies_pi ON occupancies(pi)",
    "CREATE INDEX IF NOT EXISTS idx_occupancies_status ON occupancies(status)",
    "CREATE INDEX IF NOT EXISTS idx_occupancies_species ON occupancies(species)",
    "CREATE INDEX IF NOT EXISTS idx_occupancies_billing_item ON occupancies(billing_item)",
    "CREATE INDEX IF NOT EXISTS idx_occupancies_customer_type ON occupancies(customer_type)",
    "CREATE INDEX IF NOT EXISTS idx_occupancies_start_end ON occupancies(start_date, end_date)",
    "CREATE INDEX IF NOT EXISTS idx_placement_tasks_room_id ON placement_tasks(target_room_id)",
    "CREATE INDEX IF NOT EXISTS idx_placement_tasks_status ON placement_tasks(status)",
    "CREATE INDEX IF NOT EXISTS idx_placement_tasks_move_in_date ON placement_tasks(planned_move_in_date)",
    "CREATE INDEX IF NOT EXISTS idx_experiment_applications_iacuc ON experiment_applications(iacuc)",
    "CREATE INDEX IF NOT EXISTS idx_experiment_applications_raw_iacuc ON experiment_applications(raw_iacuc)",
    "CREATE INDEX IF NOT EXISTS idx_experiment_applications_pi ON experiment_applications(pi)",
    "CREATE INDEX IF NOT EXISTS idx_quantity_sheets_month ON quantity_sheets(month)",
    "CREATE INDEX IF NOT EXISTS idx_quantity_sheets_iacuc ON quantity_sheets(iacuc)",
    "CREATE INDEX IF NOT EXISTS idx_quantity_sheets_pi ON quantity_sheets(pi)",
    "CREATE INDEX IF NOT EXISTS idx_quantity_sheets_month_updated ON quantity_sheets(month DESC, updated_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_quantity_sheets_iacuc_month ON quantity_sheets(iacuc, month DESC)",
    "CREATE INDEX IF NOT EXISTS idx_quantity_sheets_pi_month ON quantity_sheets(pi, month DESC)",
    "CREATE INDEX IF NOT EXISTS idx_quantity_sheets_room_month ON quantity_sheets(room_name, month DESC)",
    "CREATE INDEX IF NOT EXISTS idx_intake_batches_status ON intake_batches(status)",
    "CREATE INDEX IF NOT EXISTS idx_intake_batches_intake_date ON intake_batches(intake_date)",
    "CREATE INDEX IF NOT EXISTS idx_intake_batches_iacuc ON intake_batches(iacuc)",
    "CREATE INDEX IF NOT EXISTS idx_intake_batches_status_date ON intake_batches(status, intake_date DESC)",
    "CREATE INDEX IF NOT EXISTS idx_intake_batches_pi_date ON intake_batches(pi, intake_date DESC)",
    "CREATE INDEX IF NOT EXISTS idx_intake_batches_owner_date ON intake_batches(owner, intake_date DESC)",
    "CREATE INDEX IF NOT EXISTS idx_intake_batches_room_date ON intake_batches(room_name, intake_date DESC)",
    "CREATE INDEX IF NOT EXISTS idx_intake_batches_updated ON intake_batches(updated_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_billing_statements_iacuc_month ON billing_statements(iacuc, month)",
    "CREATE INDEX IF NOT EXISTS idx_billing_statement_lines_statement_id ON billing_statement_lines(statement_id)",
    "CREATE INDEX IF NOT EXISTS idx_billing_candidate_snapshots_month ON billing_candidate_snapshots(month DESC)",
    "CREATE INDEX IF NOT EXISTS idx_billing_candidate_snapshots_pi ON billing_candidate_snapshots(pi COLLATE NOCASE)",
    "CREATE INDEX IF NOT EXISTS idx_billing_candidate_snapshots_amount ON billing_candidate_snapshots(total_amount DESC)",
    "CREATE INDEX IF NOT EXISTS idx_billing_candidate_snapshots_updated ON billing_candidate_snapshots(updated_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_billing_candidate_snapshots_source_stale ON billing_candidate_snapshots(source_type, is_stale)",
    "CREATE INDEX IF NOT EXISTS idx_billing_candidate_snapshots_source_month_pi ON billing_candidate_snapshots(source_type, month DESC, pi COLLATE NOCASE)",
    "CREATE INDEX IF NOT EXISTS idx_billing_candidate_snapshots_source_amount ON billing_candidate_snapshots(source_type, total_amount DESC, month DESC, pi COLLATE NOCASE)",
    "CREATE INDEX IF NOT EXISTS idx_billing_workflows_month ON billing_workflows(month)",
    "CREATE INDEX IF NOT EXISTS idx_billing_workflows_status ON billing_workflows(workflow_status)",
    "CREATE INDEX IF NOT EXISTS idx_billing_versions_workflow_id ON billing_statement_versions(workflow_id)",
    "CREATE INDEX IF NOT EXISTS idx_billing_version_lines_version_id ON billing_statement_version_lines(version_id)",
    "CREATE INDEX IF NOT EXISTS idx_billing_events_workflow_id ON billing_workflow_events(workflow_id)",
    "CREATE INDEX IF NOT EXISTS idx_reimbursement_records_month ON reimbursement_records(month)",
    "CREATE INDEX IF NOT EXISTS idx_reimbursement_records_pi ON reimbursement_records(pi)",
    "CREATE INDEX IF NOT EXISTS idx_reimbursement_records_status ON reimbursement_records(reimbursement_status)",
    "CREATE INDEX IF NOT EXISTS idx_reimbursement_records_workflow_id ON reimbursement_records(workflow_id)",
    "CREATE INDEX IF NOT EXISTS idx_project_sync_snapshots_imported_at ON project_sync_snapshots(imported_at)",
    "CREATE INDEX IF NOT EXISTS idx_audit_events_at ON audit_events(at)",
    "CREATE INDEX IF NOT EXISTS idx_sessions_user_id ON sessions(user_id)",
    "CREATE INDEX IF NOT EXISTS idx_sessions_expires_at ON sessions(expires_at)",
    "CREATE INDEX IF NOT EXISTS idx_catalog_nodes_module ON inspection_catalog_nodes(version, module_code, sort_order)",
    "CREATE INDEX IF NOT EXISTS idx_animal_inspections_room_updated ON animal_inspections(room_id, updated_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_animal_inspections_status_updated ON animal_inspections(status, updated_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_animal_inspections_created_by ON animal_inspections(created_by, updated_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_animal_answers_inspection ON animal_inspection_answers(inspection_id, module_code)",
    "CREATE INDEX IF NOT EXISTS idx_animal_findings_room_status ON animal_inspection_findings(room_id, status, severity, updated_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_animal_findings_recheck ON animal_inspection_findings(recheck_due_at, status)",
    "CREATE INDEX IF NOT EXISTS idx_animal_attachments_finding ON animal_inspection_attachments(finding_id, created_at)",
)


def create_performance_indexes(conn):
    for statement in INDEX_STATEMENTS:
        conn.execute(statement)
